#!/bin/bash

##############################
#检测Logwatch是否安装
##############################

updatedb

ENV_PATH=../env_config

#查看是否存在logwatch的可执行文件
locate   rkhunter  | grep  "\/rkhunter$"  |  grep  "bin/"


#查看"Check_Rkhunter"所在的行号

LINE_NUM=`grep  -n  "Check_Rkhunter"   $ENV_PATH  |  awk -F:  '{print $1}'`

#在"Check_Rkhunter"行之后添加一行

if  [  `echo  $?` == 0 ]
then
	sed  -ie  "/Check_Rkhunter/a \'Check_Rkhunter\':\'YES\'" $ENV_PATH
else
	sed  -ie  "/Check_Rkhunter/a \'Check_Rkhunter\':\'NO\'" $ENV_PATH

#删除原来的"Check_Rkhunter"行

sed -i  ''$LINE_NUM'd'   $ENV_PATH