#!/bin/bash

##############################
#检测被锁定密码的账号
##############################

updatedb

ENV_PATH=../env_config


#查看被锁定密码的账号列表

grep    ':!!'   /etc/shadow  |  awk  -F :  '{print  $1}'  >  ./cache.tmp

#为每一个账号添加单引号
sed   -i  "s/$/'/g"  cache.tmp 
sed   -i  "s/^/'/g"  cache.tmp 

#将cache.tmp文件中的回车换行转换成","逗号
 sed   -i    ':t;N;s/\n/,/;b t'    cache.tmp 



#查看"Check_Logcheck"所在的行号

LINE_NUM=`grep  -n  "Check_Logcheck"   $ENV_PATH  |  awk -F:  '{print $1}'`

#在"Check_Logcheck"行之后添加一行

if  [  `echo  $?` == 0 ]
then
	sed  -ie  "/Check_Logcheck/a \'Check_Logcheck\':\'YES\'" $ENV_PATH
else
	sed  -ie  "/Check_Logcheck/a \'Check_Logcheck\':\'NO\'" $ENV_PATH

#删除原来的"Check_Logcheck"行

sed -i  ''$LINE_NUM'd'   $ENV_PATH