#!/bin/bash

##############################
#检测chkrootkit是否安装
##############################

updatedb

ENV_PATH=../env_config

#查看是否存在chkrootkit的可执行文件
locate  chkrootkit  | grep  "\/chkrootkit$" |  grep  "bin/"


#查看"Check_Chkrootkit"所在的行号

LINE_NUM=`grep  -n  "Check_Chkrootkit"   $ENV_PATH  |  awk -F:  '{print $1}'`

#在"Check_Chkrootkit"行之后添加一行

if  [  `echo  $?` == 0 ]
then
	sed  -ie  "/Check_Chkrootkit/a \'Check_Chkrootkit\':\'YES\'" $ENV_PATH
else
	sed  -ie  "/Check_Chkrootkit/a \'Check_Chkrootkit\':\'NO\'" $ENV_PATH

#删除原来的"Check_Chkrootkit"行

sed -i  ''$LINE_NUM'd'   $ENV_PATH